### PR TITLE
storage: add depth parameter to LinkStorage

### PR DESCRIPTION
**Pull request by slint**
* Adds a "depth" parameter to the LinkStorage class which allows
  deciding the max depth at which symlinks will be created up to.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Hey, nothing wrong with dropping support for old Python versions, but silently doing so in a point release without so much as a changelog entry (and proper `python_requires` restrictions!) isn't cool... 😞

**Comment by slint** [comment]
Oh God, you're right I got in "auto"-mode and I didn't even think about it :S. We've been soft-dropping Python 2 support (i.e. removing from the Travis build) in most Invenio modules in the past months. 

But the intent is not to actually if possible keep Python 2 compatibility if it's easy. I can remove the `os.scandir` call in a `v1.0.3` release. I wouldn't yet add a `python_requires` since I think that would then prevent anyone from installing the package with Python 2 (even if it works).

**Comment by ThiefMaster** [comment]
> I wouldn't yet add a python_requires since I think that would then prevent anyone from installing the package with Python 2 (even if it works).

It's indeed too late for this, since you'd have to yank 1.0.2 and 1.0.3 for it to be efficient. My recommendation would be to release 1.0.4 that restores Python 2.7 support (ie no `yield from`), and in whatever future release (2.0.0?) explicitly drops it again, you can then add `python_requires` to ensure this version is not offered to unsupported versions. That way `pip list --outdated` won't show a new version either if it's not supported by your python version.

**Comment by lnielsen** [comment]
Sorry about the mishap - I didn't realise that Indico was on Python 2.7.

We didn't consider dropping Python 2.7 tests (and thereby Python 2.7 support) as a feature change simply because of the End-Of-Life of Python 2.7, and that we implemented a policy in Invenio of not supporting unsupported Python versions. As Alex said, the intention though was not to start breaking Python 2 compatibility this fast :-)

**Pull request merged**
