### PR TITLE
npm: change deps merging algorithm

### LINKED ISSUE #38: Dependency on old `node-semver` package breaks actual `semver` package
I ran into hard-to-debug troubles that in the end were rooted in the problem that

* `node-semver` was using the module name `semver` in version [`0.1.1`](https://github.com/podhmo/python-node-semver/tree/0.1.1)
* This invenio package pulls that version as a dependency

Leading to problems when I installed packages that install the **package** `semver`, which also uses `semver` as module name.

## Expected behavior

No problems when installing [semver](https://github.com/python-semver/python-semver) package

## Solution

* ~~Update to most recent `node-semver` version [0.9](https://github.com/podhmo/python-node-semver/tree/master)~~
* ~~change `semver` to `nodesemver` [here](https://github.com/inveniosoftware/pywebpack/blob/master/pywebpack/helpers.py#L18)~~
* ~~making sure that the updated version is used upstream when installing InvenioRDM from master~~

## EDIT

* We were not the first ones stumbling on the problem with the module clash: https://github.com/podhmo/python-node-semver/issues/39
* Also, consider this: https://github.com/podhmo/python-node-semver/issues/49

Just updating the dependency to `0.9.0` results in *changed behavior* - `node-semver` in newer versions turns out to work with **Python** semver strings, not **JS** ones (what it is used for). Hence simply upgrading yields errors, because versions from a `package.json` such as `^7.9.0` are not valid Python semver strings (different syntax).

A solution would mean migrating to a package that **actually** checks npm-style semver strings, or doing something else.

### PR DESCRIPTION
**Pull request by ntarocco**
- removes node-semver/semver dependency, given the breaking changes of the latest version.
- implements semver comparison, following specs.
- raises when merging deps with incompatible major versions.
- closes https://github.com/inveniosoftware/pywebpack/issues/38

### CODE REVIEW

**Comment by ntarocco** [comment]
This removes the `node-semver/semver` dependency, it will have to be released as a major.

**Review by zzacharo — APPROVED** [review]
LGTM

**Comment by ntarocco** [comment]
Improved error handling, example message logged in the console:
```
pywebpack.errors.MergeConflictError: Incompatible major versions for package react-invenio-forms: current version is ^1.0.0, incoming version is ^2.0.0. Conflicting dependency found in /Users/nico/.local/share/virtualenvs/my-site-6hzgyFAC/lib/python3.9/site-packages/invenio_app_rdm/theme/assets/semantic-ui
```

**Comment by ntarocco** [comment]
Closed and re-opened to run tests on CI

**Comment by ThiefMaster** [comment]
FYI github has a button to re-run CI jobs ;)

**Comment by ntarocco** [comment]
> FYI github has a button to re-run CI jobs ;)

I am aware, but it looks like that it is not working (well) for very very old runs ;)

**Pull request merged**
